version: '3.7'
services:
  back:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./:/usr/src/freedom
    ports:
      - 8002:8002
    expose: [8002]
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=q1726354
      - POSTGRES_DB=freedom
volumes:
  postgres_data:
